services:
  server:
    build: ./server
    ports:
      - '8000:8000'
    volumes:
      - ./server:/app
    command: python manage.py runserver 0.0.0.0:8000

  client:
    image: node:20
    working_dir: /app
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
    command: sh -c 'npm install && npm run dev'
