# Generated by Django 5.1.2 on 2024-10-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='Member',
        ),
    ]
